spring.application.name=agua-facil

spring.datasource.url=jdbc:mysql://localhost:3306/agua_facil?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=agua-facil
spring.datasource.password=ajdNe87#1G
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect